Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-03, with the labels that each got.

#52 Mapping external time series to models
  docs/uml/InputDatamodelConcept.puml
  src/main/java/edu/ie3/dataconnection/source/WeatherSource.java
  src/main/java/edu/ie3/models/StandardUnits.java
  src/main/java/edu/ie3/models/input/LoadProfileInput.java
  src/main/java/edu/ie3/models/timeseries/HeatAndPTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/HeatAndSTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/HeatDemandTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/IndividualTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/PTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/RepetitiveTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/STimeSeries.java
  src/main/java/edu/ie3/models/timeseries/TimeSeries.java
  src/main/java/edu/ie3/models/timeseries/mapping/HeatAndPTimeSeriesMap.java
  src/main/java/edu/ie3/models/timeseries/mapping/HeatAndSTimeSeriesMap.java
  src/main/java/edu/ie3/models/timeseries/mapping/HeatTimeSeriesMap.java
  src/main/java/edu/ie3/models/timeseries/mapping/PTimeSeriesMap.java
  src/main/java/edu/ie3/models/timeseries/mapping/STimeSeriesMap.java
  src/main/java/edu/ie3/models/value/HeatAndPValue.java
  src/main/java/edu/ie3/models/value/HeatAndSValue.java
  src/main/java/edu/ie3/models/value/HeatDemandValue.java
  src/main/java/edu/ie3/models/value/PValue.java
  src/main/java/edu/ie3/models/value/SValue.java
  src/main/java/edu/ie3/models/value/WeatherValue.java
Labels: enhancement

#55 Introduce voltage level data model
  src/main/java/edu/ie3/exceptions/AggregationException.java
  src/main/java/edu/ie3/exceptions/VoltageLevelException.java
  src/main/java/edu/ie3/io/factory/EntityData.java
  src/main/java/edu/ie3/io/factory/input/NodeInputFactory.java
  src/main/java/edu/ie3/models/GermanVoltageLevel.java
  src/main/java/edu/ie3/models/VoltageLevel.java
  src/main/java/edu/ie3/models/input/NodeInput.java
  src/main/java/edu/ie3/models/input/aggregated/AggregatedGridInput.java
  src/main/java/edu/ie3/models/voltagelevels/CommonVoltageLevel.java
  src/main/java/edu/ie3/models/voltagelevels/GermanVoltageLevelUtils.java
  src/main/java/edu/ie3/models/voltagelevels/VoltageLevel.java
  src/main/java/edu/ie3/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/io/factory/input/NodeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/models/CommonVoltageLevelTest.groovy
  src/test/groovy/edu/ie3/models/GermanVoltageLevelUtilsTest.groovy
  src/test/groovy/edu/ie3/models/input/aggregated/AggregatedGridInputTest.groovy
Labels: enhancement

#57 Add methods to explore the near surrounding of the queried time instant
  src/main/java/edu/ie3/models/input/LoadProfileInput.java
  src/main/java/edu/ie3/models/timeseries/IndividualTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/RepetitiveTimeSeries.java
  src/main/java/edu/ie3/models/timeseries/TimeSeries.java
  src/test/groovy/edu/ie3/models/timeseries/IndividualTimeSeriesSpec.groovy
  src/test/groovy/edu/ie3/models/timeseries/IntValue.groovy
Labels: bug, enhancement

#64 Container model for complete data set
  docs/test/complexTopology.drawio
  docs/test/complexTopology.pdf
  docs/uml/ModelContainerConcept.puml
  src/main/java/edu/ie3/datamodel/dataconnection/source/RawGridSource.java
  src/main/java/edu/ie3/datamodel/dataconnection/source/SystemParticipantSource.java
  src/main/java/edu/ie3/datamodel/exceptions/InvalidGridException.java
  src/main/java/edu/ie3/datamodel/graph/SubGridTopologyGraph.java
  src/main/java/edu/ie3/datamodel/models/OperationTime.java
  src/main/java/edu/ie3/datamodel/models/input/aggregated/AggregatedEntities.java
  src/main/java/edu/ie3/datamodel/models/input/aggregated/AggregatedGridInput.java
  src/main/java/edu/ie3/datamodel/models/input/aggregated/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/aggregated/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/aggregated/SystemParticipantElements.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/Transformer3WTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/container/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/GridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/InputContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/JointGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/SubGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/SystemParticipants.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/main/java/edu/ie3/datamodel/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/Transformer3WTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/aggregated/AggregatedGridInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilTest.groovy
  src/test/groovy/edu/ie3/test/common/ComplexTopology.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
Labels: enhancement

#68 Adding reference for standard load profiles
  src/main/java/edu/ie3/datamodel/exceptions/ParsingException.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactory.java
  src/main/java/edu/ie3/datamodel/models/BdewLoadProfile.java
  src/main/java/edu/ie3/datamodel/models/LoadProfileType.java
  src/main/java/edu/ie3/datamodel/models/PowerSystemLoadProfileType.java
  src/main/java/edu/ie3/datamodel/models/StandardLoadProfile.java
  src/main/java/edu/ie3/datamodel/models/input/LoadProfileInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/StandardLoadProfileTest.groovy
Labels: enhancement

#72 Extending the information held by the SubGridGate
  src/main/java/edu/ie3/datamodel/graph/SubGridGate.java
  src/main/java/edu/ie3/datamodel/graph/SubGridTopologyGraph.java
  src/main/java/edu/ie3/datamodel/models/input/connector/ConnectorPort.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilTest.groovy
  src/test/groovy/edu/ie3/test/common/ComplexTopology.groovy
Labels: enhancement

#23 csv writer for result entities
  build.gradle
  src/main/java/edu/ie3/datamodel/dataconnection/source/TypeSource.java
  src/main/java/edu/ie3/datamodel/exceptions/ConnectorException.java
  src/main/java/edu/ie3/datamodel/exceptions/ProcessorProviderException.java
  src/main/java/edu/ie3/datamodel/exceptions/SinkException.java
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/connectors/DataConnector.java
  src/main/java/edu/ie3/datamodel/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/sink/DataSink.java
  src/main/java/edu/ie3/datamodel/io/source/DataSource.java
  src/main/java/edu/ie3/datamodel/io/source/RawGridSource.java
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/main/java/edu/ie3/datamodel/io/source/TypeSource.java
  src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/WholesalePriceSource.java
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/resources/log4j2-test.xml
Labels: enhancement

#80 Adapting ValidationUtils to commonly known assumptions
  .gitignore
  src/main/java/edu/ie3/datamodel/models/input/container/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/GridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/InputContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/JointGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/SubGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/SystemParticipants.java
  src/main/java/edu/ie3/datamodel/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
Labels: bug

#74 Extend processors and csv file sink
  docs/uml/InputDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/factory/input/NodeInputFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/processor/input/AssetInputProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/datamodel/models/BdewLoadProfile.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageStrategy.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/BmTypeInput.java
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/AssetInputProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilTest.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/resources/log4j2-test.xml
Labels: enhancement

#83 Adding processor for graphic inputs
  docs/uml/main/DataSourceClassDiagramm.puml
  docs/uml/main/InputDataDeployment.puml
  docs/uml/main/InputDatamodelConcept.puml
  docs/uml/main/ModelContainerConcept.puml
  docs/uml/main/OutputDatamodelConcept.puml
  docs/uml/test/TestDataHierarchy.puml
  src/main/java/edu/ie3/datamodel/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/processor/input/GraphicInputProcessor.java
  src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/GraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/LineGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/value/WeatherValue.java
  src/main/java/edu/ie3/datamodel/utils/CoordinateUtils.java
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/AssetInputProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/GraphicInputProcessorTest.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
Labels: enhancement

#88 Formatting groovy scripts
  build.gradle
  gradle/scripts/checkJavaVersion.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/mavenCentralPublish.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/tests.gradle
  src/test/groovy/edu/ie3/datamodel/io/FileNamingStrategyTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/AssetInputEntityFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/LineInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/MeasurementUnitInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/NodeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/SwitchInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/ThermalBusInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/ThermalHouseInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/Transformer2WInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/Transformer3WInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/BmInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/ChpInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/HpInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/PvInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/StorageInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/WecInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/ConnectorResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/NodeResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/ThermalResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/LineTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/Transformer2WTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/Transformer3WTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/AssetInputProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/GraphicInputProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/CommonVoltageLevelTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/GermanVoltageLevelUtilsTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/StandardLoadProfileTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/timeseries/IndividualTimeSeriesSpec.groovy
  src/test/groovy/edu/ie3/datamodel/models/timeseries/IntValue.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilTest.groovy
  src/test/groovy/edu/ie3/test/common/ComplexTopology.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/groovy/edu/ie3/test/helper/FactoryTestHelper.groovy
Labels: documentation

#85 Fixing bugs in common voltage levels
  Jenkinsfile
  build.gradle
  gradle/scripts/mavenCentralPublish.gradle
  src/main/java/edu/ie3/datamodel/models/voltagelevels/CommonVoltageLevel.java
  src/main/java/edu/ie3/datamodel/models/voltagelevels/GermanVoltageLevelUtils.java
  src/main/java/edu/ie3/datamodel/models/voltagelevels/VoltageLevel.java
  src/test/groovy/edu/ie3/datamodel/io/processor/input/AssetInputProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/CommonVoltageLevelTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilTest.groovy
Labels: bug
