Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-02, with the labels that each got.

#19 Mk/#8 replace optional use
  build.gradle
  src/main/java/edu/ie3/models/Operable.java
  src/main/java/edu/ie3/models/OperationTime.java
  src/main/java/edu/ie3/models/input/AssetInput.java
  src/main/java/edu/ie3/models/input/MeasurementUnitInput.java
  src/main/java/edu/ie3/models/input/NodeInput.java
  src/main/java/edu/ie3/models/input/connector/ConnectorInput.java
  src/main/java/edu/ie3/models/input/connector/LineInput.java
  src/main/java/edu/ie3/models/input/connector/SwitchInput.java
  src/main/java/edu/ie3/models/input/connector/Transformer2WInput.java
  src/main/java/edu/ie3/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/models/input/connector/TransformerInput.java
  src/main/java/edu/ie3/models/input/system/BmInput.java
  src/main/java/edu/ie3/models/input/system/ChpInput.java
  src/main/java/edu/ie3/models/input/system/EvInput.java
  src/main/java/edu/ie3/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/models/input/system/HpInput.java
  src/main/java/edu/ie3/models/input/system/LoadInput.java
  src/main/java/edu/ie3/models/input/system/PvInput.java
  src/main/java/edu/ie3/models/input/system/StorageInput.java
  src/main/java/edu/ie3/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/models/input/system/WecInput.java
  src/main/java/edu/ie3/models/input/thermal/ThermalBusInput.java
  src/test/java/edu/ie3/models/OperationTimeBuilderTest.java
  src/test/java/edu/ie3/models/OperationTimeTest.java
Labels: enhancement

#21 Extend result factories with field to value mapping methods
  build.gradle
  src/main/java/edu/ie3/exceptions/EntityProcessorException.java
  src/main/java/edu/ie3/io/factory/EntityFactory.java
  src/main/java/edu/ie3/io/factory/SimpleEntityFactory.java
  src/main/java/edu/ie3/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/models/StandardUnits.java
  src/test/groovy/edu/ie3/io/factory/result/ConnectorResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/NodeResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ThermalSinkResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/java/edu/ie3/models/OperationTimeTest.java
Labels: enhancement

#25 FileNamingStrategy proposal incl. tests
  src/main/java/edu/ie3/io/FileNamingStrategy.java
  src/test/groovy/edu/ie3/io/FileNamingStrategyTest.groovy
Labels: enhancement

#34 ck/#34-enhancingStandardUnits
  src/main/java/edu/ie3/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/io/factory/result/NodeResultFactory.java
  src/main/java/edu/ie3/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/io/factory/result/ThermalSinkResultFactory.java
  src/main/java/edu/ie3/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/models/StandardUnits.java
  src/main/java/edu/ie3/models/input/NodeInput.java
  src/main/java/edu/ie3/models/input/connector/type/LineTypeInput.java
  src/main/java/edu/ie3/models/input/connector/type/Transformer2WTypeInput.java
  src/main/java/edu/ie3/models/input/connector/type/Transformer3WTypeInput.java
  src/main/java/edu/ie3/models/input/system/LoadInput.java
  src/main/java/edu/ie3/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/models/result/ThermalSinkResult.java
  src/test/groovy/edu/ie3/io/factory/result/ConnectorResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/NodeResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ThermalSinkResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/processor/result/ResultEntityProcessorTest.groovy
Labels: documentation, enhancement

#33 ck/#33-overridingGetterAndSetter
  src/main/java/edu/ie3/models/input/connector/Transformer3WInput.java
Labels: bug

#35 Added ResultEntityFactory + set java version to 1.8
  .travis.yml
  Jenkinsfile
  build.gradle
  src/main/java/edu/ie3/io/FileNamingStrategy.java
  src/main/java/edu/ie3/io/factory/SimpleEntityFactory.java
  src/main/java/edu/ie3/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/io/factory/result/NodeResultFactory.java
  src/main/java/edu/ie3/io/factory/result/ResultEntityFactory.java
  src/main/java/edu/ie3/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/io/factory/result/ThermalSinkResultFactory.java
  src/main/java/edu/ie3/models/OperationTime.java
  src/test/java/edu/ie3/models/OperationTimeTest.java
Labels: enhancement

#30 cm/#29-add-DistanceWeightedGraph
  build.gradle
  src/main/java/edu/ie3/graph/DistanceWeightedEdge.java
  src/main/java/edu/ie3/graph/DistanceWeightedGraph.java
Labels: enhancement

#36 ck/#35 thermal output models
  docs/uml/OutputDatamodelConcept.puml
  src/main/java/edu/ie3/io/FileNamingStrategy.java
  src/main/java/edu/ie3/io/factory/result/ThermalResultFactory.java
  src/main/java/edu/ie3/io/factory/result/ThermalSinkResultFactory.java
  src/main/java/edu/ie3/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/models/StandardUnits.java
  src/main/java/edu/ie3/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/models/result/ThermalSinkResult.java
  src/main/java/edu/ie3/models/result/thermal/CylindricalStorageResult.java
  src/main/java/edu/ie3/models/result/thermal/ThermalHouseResult.java
  src/main/java/edu/ie3/models/result/thermal/ThermalSinkResult.java
  src/main/java/edu/ie3/models/result/thermal/ThermalStorageResult.java
  src/main/java/edu/ie3/models/result/thermal/ThermalUnitResult.java
  src/test/groovy/edu/ie3/io/FileNamingStrategyTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ThermalResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ThermalSinkResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/processor/result/ResultEntityProcessorTest.groovy
Labels: documentation, enhancement

#26 Asset type input factories
  src/main/java/edu/ie3/io/factory/EntityData.java
  src/main/java/edu/ie3/io/factory/EntityFactory.java
  src/main/java/edu/ie3/io/factory/SimpleEntityFactory.java
  src/main/java/edu/ie3/io/factory/input/AssetTypeInputEntityFactory.java
  src/main/java/edu/ie3/io/factory/input/LineTypeInputFactory.java
  src/main/java/edu/ie3/io/factory/input/SystemParticipantTypeInputFactory.java
  src/main/java/edu/ie3/io/factory/input/Transformer2WTypeInputFactory.java
  src/main/java/edu/ie3/io/factory/input/Transformer3WTypeInputFactory.java
  src/main/java/edu/ie3/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/io/factory/result/NodeResultFactory.java
  src/main/java/edu/ie3/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/io/factory/result/ThermalResultFactory.java
  src/main/java/edu/ie3/models/StandardUnits.java
  src/main/java/edu/ie3/models/input/system/type/EvTypeInput.java
  src/test/groovy/edu/ie3/io/factory/input/LineTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/input/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/input/Transformer2WTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/input/Transformer3WTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ConnectorResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/NodeResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/result/ThermalResultFactoryTest.groovy
  src/test/groovy/edu/ie3/test/helper/FactoryTestHelper.groovy
Labels: enhancement

#41 Addressing #40 - added NO_OPERATOR field in OperatorInput
  src/main/java/edu/ie3/models/input/OperatorInput.java
Labels: enhancement

#44 ds/#37-gridInput
  src/main/java/edu/ie3/dataconnection/source/RawGridSource.java
  src/main/java/edu/ie3/dataconnection/source/SystemParticipantSource.java
  src/main/java/edu/ie3/models/Operable.java
  src/main/java/edu/ie3/models/input/AssetInput.java
  src/main/java/edu/ie3/models/input/AssetTypeInput.java
  src/main/java/edu/ie3/models/input/MeasurementUnitInput.java
  src/main/java/edu/ie3/models/input/NodeInput.java
  src/main/java/edu/ie3/models/input/OperatorInput.java
  src/main/java/edu/ie3/models/input/RandomLoadParameters.java
  src/main/java/edu/ie3/models/input/aggregated/AggregatedGridInput.java
  src/main/java/edu/ie3/models/input/aggregated/GraphicElements.java
  src/main/java/edu/ie3/models/input/aggregated/RawGridElements.java
  src/main/java/edu/ie3/models/input/aggregated/SystemParticipantElements.java
  src/main/java/edu/ie3/models/input/connector/ConnectorInput.java
  src/main/java/edu/ie3/models/input/connector/LineInput.java
  src/main/java/edu/ie3/models/input/connector/SwitchInput.java
  src/main/java/edu/ie3/models/input/connector/Transformer2WInput.java
  src/main/java/edu/ie3/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/models/input/connector/TransformerInput.java
  src/main/java/edu/ie3/models/input/connector/type/LineTypeInput.java
  src/main/java/edu/ie3/models/input/connector/type/Transformer2WTypeInput.java
  src/main/java/edu/ie3/models/input/connector/type/Transformer3WTypeInput.java
  src/main/java/edu/ie3/models/input/graphics/GraphicInput.java
  src/main/java/edu/ie3/models/input/graphics/LineGraphicInput.java
  src/main/java/edu/ie3/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/models/input/system/BmInput.java
  src/main/java/edu/ie3/models/input/system/ChpInput.java
  src/main/java/edu/ie3/models/input/system/EvInput.java
  src/main/java/edu/ie3/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/models/input/system/HpInput.java
  src/main/java/edu/ie3/models/input/system/LoadInput.java
  src/main/java/edu/ie3/models/input/system/PvInput.java
  src/main/java/edu/ie3/models/input/system/StorageInput.java
  src/main/java/edu/ie3/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/models/input/system/WecInput.java
  src/main/java/edu/ie3/models/input/system/characteristic/AssetCharacteristicInput.java
  src/main/java/edu/ie3/models/input/system/characteristic/WecCharacteristicInput.java
  src/main/java/edu/ie3/models/input/system/type/BmTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/ChpTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/EvTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/HpTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/SystemParticipantTypeInput.java
  src/main/java/edu/ie3/models/input/system/type/WecTypeInput.java
  src/main/java/edu/ie3/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/models/input/thermal/ThermalHouseInput.java
  src/main/java/edu/ie3/models/input/thermal/ThermalUnitInput.java
  src/main/java/edu/ie3/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/io/factory/input/LineTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/input/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/io/factory/input/Transformer2WTypeInputFactoryTest.groovy
Labels: enhancement

#50 Use the correct unit for admittance per length
  src/main/java/edu/ie3/models/StandardUnits.java
Labels: bug
