Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-06, with the labels that each got.

#156 New constructors for container classes
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/models/input/container/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/SystemParticipants.java
  src/test/groovy/edu/ie3/datamodel/models/input/container/GraphicElementsTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/container/RawGridElementsTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/container/SystemParticipantsTest.groovy
Labels: enhancement

#160 DistanceWeightedGraph Utility method
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/graph/DistanceWeightedEdge.java
  src/main/java/edu/ie3/datamodel/graph/DistanceWeightedGraph.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilsTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/GridAndGeoUtilsTest.groovy
Labels: enhancement

#162 Introduction of copy builders for immutable grid assets
  CHANGELOG.md
  docs/readthedocs/models/models.rst
  src/main/java/edu/ie3/datamodel/models/UniqueEntity.java
  src/main/java/edu/ie3/datamodel/models/input/AssetInput.java
  src/main/java/edu/ie3/datamodel/models/input/MeasurementUnitInput.java
  src/main/java/edu/ie3/datamodel/models/input/NodeInput.java
  src/main/java/edu/ie3/datamodel/models/input/OperatorInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/ConnectorInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/LineInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/SwitchInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer2WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/TransformerInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/GraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/LineGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/HpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/PvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/test/groovy/edu/ie3/datamodel/models/input/MeasurementUnitInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/NodeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/OperatorInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/connector/LineInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/connector/SwitchInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/connector/Transformer2WInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/connector/Transformer3WInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/graphics/LineGraphicInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/graphics/NodeGraphicInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/BmInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/ChpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/FixedFeedInInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/HpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/LoadInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/PvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/StorageInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/WecInputTest.groovy
Labels: enhancement

#166 Adds Regex to modify JSON Stings to match csv spec.
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/BufferedCsvWriter.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvGraphicSourceTest.groovy
  src/test/groovy/edu/ie3/test/common/ComplexTopology.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
  src/test/resources/testGridFiles/graphics/line_graphic_input.csv
  src/test/resources/testGridFiles/graphics/node_graphic_input.csv
  src/test/resources/testGridFiles/grid/line_input.csv
  src/test/resources/testGridFiles/grid/measurement_unit_input.csv
  src/test/resources/testGridFiles/grid/node_input.csv
  src/test/resources/testGridFiles/grid/switch_input.csv
  src/test/resources/testGridFiles/grid/transformer2w_input.csv
  src/test/resources/testGridFiles/grid/transformer3w_input.csv
  src/test/resources/testGridFiles/grid_empty/line_input.csv
  src/test/resources/testGridFiles/grid_empty/measurement_unit_input.csv
  src/test/resources/testGridFiles/grid_empty/node_input.csv
  src/test/resources/testGridFiles/grid_empty/switch_input.csv
  src/test/resources/testGridFiles/grid_empty/transformer2w_input.csv
  src/test/resources/testGridFiles/grid_empty/transformer3w_input.csv
  src/test/resources/testGridFiles/grid_malformed/line_input.csv
  src/test/resources/testGridFiles/grid_malformed/measurement_unit_input.csv
  src/test/resources/testGridFiles/grid_malformed/node_input.csv
  src/test/resources/testGridFiles/grid_malformed/switch_input.csv
  src/test/resources/testGridFiles/grid_malformed/transformer2w_input.csv
  src/test/resources/testGridFiles/grid_malformed/transformer3w_input.csv
  src/test/resources/testGridFiles/participants/bm_input.csv
  src/test/resources/testGridFiles/participants/chp_input.csv
  src/test/resources/testGridFiles/participants/cylindrical_storage_input.csv
  src/test/resources/testGridFiles/participants/ev_input.csv
  src/test/resources/testGridFiles/participants/fixed_feed_in_input.csv
  src/test/resources/testGridFiles/participants/hp_input.csv
  src/test/resources/testGridFiles/participants/load_input.csv
  src/test/resources/testGridFiles/participants/pv_input.csv
  src/test/resources/testGridFiles/participants/storage_input.csv
  src/test/resources/testGridFiles/participants/thermal_bus_input.csv
  src/test/resources/testGridFiles/participants/wec_input.csv
  src/test/resources/testGridFiles/thermal/cylindrical_storage_input.csv
  src/test/resources/testGridFiles/thermal/thermal_bus_input.csv
  src/test/resources/testGridFiles/thermal/thermal_house_input.csv
  src/test/resources/testGridFiles/types/bm_type_input.csv
  src/test/resources/testGridFiles/types/chp_type_input.csv
  src/test/resources/testGridFiles/types/ev_type_input.csv
  src/test/resources/testGridFiles/types/hp_type_input.csv
  src/test/resources/testGridFiles/types/line_type_input.csv
  src/test/resources/testGridFiles/types/operator_input.csv
  src/test/resources/testGridFiles/types/storage_type_input.csv
  src/test/resources/testGridFiles/types/transformer2w_type_input.csv
  src/test/resources/testGridFiles/types/transformer3w_type_input.csv
  src/test/resources/testGridFiles/types/wec_type_input.csv
Labels: bug, invalid

#168 Finalizing pull requests
  .gitattributes
  AUTHORS
  CHANGELOG.md
  CONTRIBUTING.md
  Jenkinsfile
  build.gradle
  gradle/scripts/documentation.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/javadoc.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/sphinx.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/tests.gradle
  gradle/scripts/vcs.gradle
  src/main/java/edu/ie3/datamodel/graph/DistanceWeightedGraph.java
Labels: documentation, enhancement

#173 Fix integration test task
  docs/javadoc/allclasses-frame.html
  docs/javadoc/allclasses-noframe.html
  docs/javadoc/edu/ie3/datamodel/io/connectors/InfluxDbConnector.html
  docs/javadoc/edu/ie3/datamodel/io/connectors/package-summary.html
  docs/javadoc/edu/ie3/datamodel/io/processor/ProcessorProvider.html
  docs/javadoc/edu/ie3/datamodel/io/sink/CsvFileSink.html
  docs/javadoc/edu/ie3/datamodel/io/sink/DataSink.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-frame.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-summary.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-tree.html
  docs/javadoc/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.html
  docs/javadoc/index-all.html
  docs/javadoc/overview-tree.html
  docs/readthedocs/_static/figures/uml/CharacteristicDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/ConnectorDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/DataSourceClassDiagramm.png
  docs/readthedocs/_static/figures/uml/DataSourceClassDiagramm_draft.png
  docs/readthedocs/_static/figures/uml/GraphicDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/InputDataDeployment.png
  docs/readthedocs/_static/figures/uml/InputDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/ModelContainerConcept.png
  docs/readthedocs/_static/figures/uml/OutputDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/SystemDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/TestDataHierarchy.png
  docs/readthedocs/_static/figures/uml/ThermalDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/TimeSeriesDatamodelConcept.png
  gradle/scripts/documentation.gradle
  gradle/scripts/tests.gradle
Labels: bug

#171 Removes behaviour from StorageInput
  docs/javadoc/allclasses-frame.html
  docs/javadoc/allclasses-noframe.html
  docs/javadoc/deprecated-list.html
  docs/javadoc/edu/ie3/datamodel/io/connectors/InfluxDbConnector.html
  docs/javadoc/edu/ie3/datamodel/io/connectors/package-summary.html
  docs/javadoc/edu/ie3/datamodel/io/processor/ProcessorProvider.html
  docs/javadoc/edu/ie3/datamodel/io/sink/CsvFileSink.html
  docs/javadoc/edu/ie3/datamodel/io/sink/DataSink.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-frame.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-summary.html
  docs/javadoc/edu/ie3/datamodel/io/sink/package-tree.html
  docs/javadoc/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/StorageInput.StorageInputCopyBuilder.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/StorageInput.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/StorageStrategy.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/SystemParticipantInput.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/package-frame.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/package-summary.html
  docs/javadoc/edu/ie3/datamodel/models/input/system/package-tree.html
  docs/javadoc/index-all.html
  docs/javadoc/overview-tree.html
  docs/readthedocs/_static/figures/uml/CharacteristicDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/ConnectorDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/DataSourceClassDiagramm.png
  docs/readthedocs/_static/figures/uml/DataSourceClassDiagramm_draft.png
  docs/readthedocs/_static/figures/uml/GraphicDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/InputDataDeployment.png
  docs/readthedocs/_static/figures/uml/InputDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/ModelContainerConcept.png
  docs/readthedocs/_static/figures/uml/OutputDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/SystemDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/TestDataHierarchy.png
  docs/readthedocs/_static/figures/uml/ThermalDatamodelConcept.png
  docs/readthedocs/_static/figures/uml/TimeSeriesDatamodelConcept.png
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/StorageInputFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/Processor.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageStrategy.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/StorageInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/StorageInputTest.groovy
  src/test/groovy/edu/ie3/test/common/SampleJointGrid.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/resources/testGridFiles/participants/storage_input.csv
Labels: invalid
