Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-05, with the labels that each got.

#139 added result model for heatpumps
  CHANGELOG.md
  build.gradle
  docs/uml/main/OutputDatamodelConcept.puml
  gradle/scripts/jacoco.gradle
  gradle/scripts/sonarqube.gradle
  src/main/java/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/datamodel/models/result/system/HpResult.java
  src/test/groovy/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
Labels: bug, invalid

#140 adapted build.gradle to load sonarqube.gradle correctly
  build.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/sonarqube.gradle
Labels: bug

#133 Fixes GermanVoltageLevel.parse bug
  Jenkinsfile
  src/main/java/edu/ie3/datamodel/models/voltagelevels/GermanVoltageLevelUtils.java
Labels: bug

#142 Generify InputContainer interface.allEntitiesAsList()
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/main/java/edu/ie3/datamodel/models/input/EvcsInput.java
  src/main/java/edu/ie3/datamodel/models/input/container/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/GridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/InputContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/SystemParticipants.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvcsInput.java
  src/test/groovy/edu/ie3/datamodel/io/FileNamingStrategyTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
Labels: good first issue

#150 Minor adaption in documentation
  CHANGELOG.md
  Jenkinsfile
  README.md
  build.gradle
  gradle.properties
Labels: documentation

#152 Remove invalid fields from SwitchResult
  CHANGELOG.md
  docs/uml/main/OutputDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/connectors/InfluxDbConnector.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/SwitchResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/TimeBasedWeatherValueData.java
  src/main/java/edu/ie3/datamodel/models/result/connector/SwitchResult.java
  src/main/java/edu/ie3/datamodel/models/result/system/EvcsResult.java
  src/main/java/edu/ie3/datamodel/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/result/ConnectorResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/SwitchResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ValidationUtilsTest.groovy
Labels: bug
