Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-04, with the labels that each got.

#92 Extractor for nested models
  Jenkinsfile
  docs/uml/main/InputDatamodelConcept.puml
  gradle/scripts/tests.gradle
  src/main/java/edu/ie3/datamodel/exceptions/ExtractorException.java
  src/main/java/edu/ie3/datamodel/io/extractor/Extractor.java
  src/main/java/edu/ie3/datamodel/io/extractor/Nested.java
  src/main/java/edu/ie3/datamodel/io/extractor/Node.java
  src/main/java/edu/ie3/datamodel/io/extractor/NodeC.java
  src/main/java/edu/ie3/datamodel/io/extractor/Nodes.java
  src/main/java/edu/ie3/datamodel/io/extractor/Type.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/sink/DataSink.java
  src/main/java/edu/ie3/datamodel/models/input/MeasurementUnitInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/ConnectorInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/LineInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer2WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/HpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/test/groovy/edu/ie3/datamodel/io/extractor/ExtractorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
Labels: enhancement

#93 Adds a default geoPosition
  src/main/java/edu/ie3/datamodel/io/factory/input/AssetInputEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/LineInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/NodeInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/NodeInput.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/AssetInputEntityFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/MeasurementUnitInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/Transformer3WInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
Labels: enhancement, invalid

#100 added OperatorInputFactory
  src/main/java/edu/ie3/datamodel/io/factory/input/OperatorInputFactory.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/OperatorInputFactoryTest.groovy
Labels: enhancement

#108 added GraphicInputFactories
  src/main/java/edu/ie3/datamodel/io/factory/SimpleEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/GraphicInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/LineGraphicInputEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/LineGraphicInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/NodeGraphicInputEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/NodeGraphicInputFactory.java
  src/test/groovy/edu/ie3/datamodel/io/factory/graphics/LineGraphicInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/graphics/NodeGraphicInputFactoryTest.groovy
Labels: enhancement

#106 Consolidate geo utils across data model and utils
  src/main/java/edu/ie3/datamodel/io/factory/input/LineInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/NodeInput.java
  src/main/java/edu/ie3/datamodel/utils/CoordinateTools.java
  src/main/java/edu/ie3/datamodel/utils/CoordinateUtils.java
  src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/LineInputFactoryTest.groovy
Labels: enhancement, good first issue

#95 Processing time series
  .gitignore
  docs/uml/main/InputDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/FileNamingStrategy.java
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/BufferedCsvWriter.java
  src/main/java/edu/ie3/datamodel/io/csv/CsvFileDefinition.java
  src/main/java/edu/ie3/datamodel/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/Processor.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/processor/input/InputEntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/FieldSourceToMethod.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessorKey.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/sink/DataSink.java
  src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/WholesalePriceSource.java
  src/main/java/edu/ie3/datamodel/models/StandardLoadProfile.java
  src/main/java/edu/ie3/datamodel/models/UniqueEntity.java
  src/main/java/edu/ie3/datamodel/models/input/LoadProfileInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/WecTypeInput.java
  src/main/java/edu/ie3/datamodel/models/timeseries/HeatAndPTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/HeatAndSTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/HeatDemandTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/IndividualTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/PTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/RepetitiveTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/STimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeriesEntry.java
  src/main/java/edu/ie3/datamodel/models/timeseries/individual/IndividualTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/individual/TimeBasedValue.java
  src/main/java/edu/ie3/datamodel/models/timeseries/mapping/HeatAndPTimeSeriesMap.java
  src/main/java/edu/ie3/datamodel/models/timeseries/mapping/HeatAndSTimeSeriesMap.java
  src/main/java/edu/ie3/datamodel/models/timeseries/mapping/HeatTimeSeriesMap.java
  src/main/java/edu/ie3/datamodel/models/timeseries/mapping/PTimeSeriesMap.java
  src/main/java/edu/ie3/datamodel/models/timeseries/mapping/STimeSeriesMap.java
  src/main/java/edu/ie3/datamodel/models/timeseries/repetitive/LoadProfileEntry.java
  src/main/java/edu/ie3/datamodel/models/timeseries/repetitive/LoadProfileInput.java
  src/main/java/edu/ie3/datamodel/models/timeseries/repetitive/RepetitiveTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/value/WeatherValue.java
  src/test/groovy/edu/ie3/datamodel/io/FileNamingStrategyTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/timeseries/IndividualTimeSeriesTest.groovy
  src/test/groovy/edu/ie3/test/common/TimeSeriesTestData.groovy
  src/test/groovy/edu/ie3/test/helper/UuidPrinter.groovy
Labels: enhancement

#112 Overhaul the uml diagram
  docs/uml/main/InputDataDeployment.puml
  docs/uml/main/InputDatamodelConcept.puml
  docs/uml/main/ModelContainerConcept.puml
  docs/uml/main/OutputDatamodelConcept.puml
  docs/uml/main/TimeSeriesDatamodelConcept.puml
  docs/uml/main/input/CharacteristicDatamodelConcept.puml
  docs/uml/main/input/ConnectorDatamodelConcept.puml
  docs/uml/main/input/GraphicDatamodelConcept.puml
  docs/uml/main/input/InputDatamodelConcept.puml
  docs/uml/main/input/ModelContainerConcept.puml
  docs/uml/main/input/SystemDatamodelConcept.puml
  docs/uml/main/input/ThermalDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/models/input/connector/SwitchInput.java
  src/main/java/edu/ie3/datamodel/models/input/container/JointGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/PvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/SystemParticipantTypeInput.java
  src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/individual/IndividualTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/timeseries/individual/TimeBasedValue.java
  src/main/java/edu/ie3/datamodel/models/timeseries/repetitive/RepetitiveTimeSeries.java
  src/main/java/edu/ie3/datamodel/models/value/EnergyPriceValue.java
  src/main/java/edu/ie3/datamodel/models/value/HeatAndPValue.java
  src/main/java/edu/ie3/datamodel/models/value/HeatAndSValue.java
  src/main/java/edu/ie3/datamodel/models/value/HeatDemandValue.java
  src/main/java/edu/ie3/datamodel/models/value/IrradiationValue.java
  src/main/java/edu/ie3/datamodel/models/value/PValue.java
  src/main/java/edu/ie3/datamodel/models/value/SValue.java
  src/main/java/edu/ie3/datamodel/models/value/TemperatureValue.java
  src/main/java/edu/ie3/datamodel/models/value/WeatherValue.java
  src/main/java/edu/ie3/datamodel/models/value/WindValue.java
  src/main/java/edu/ie3/datamodel/models/voltagelevels/GermanVoltageLevelUtils.java
  src/test/groovy/edu/ie3/datamodel/io/extractor/ExtractorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/PvInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTypeSourceTest.groovy
Labels: enhancement

#121 Fixing several bugs
  .travis/build.sh
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/BufferedCsvWriter.java
  src/main/java/edu/ie3/datamodel/io/factory/input/graphics/GraphicInputFactory.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/models/input/connector/LineInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/GraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/LineGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java
  src/main/java/edu/ie3/datamodel/utils/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/graphics/LineGraphicInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/graphics/NodeGraphicInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/LineInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/connector/LineInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/graphics/GraphicInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/GridAndGeoUtilsTest.groovy
Labels: bug

#126 Add method for computableSubgrids
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTestDataMeta.groovy
  src/test/groovy/edu/ie3/datamodel/utils/ContainerUtilsTest.groovy
Labels: documentation, enhancement
