Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2020-11, with the labels that each got.

#238 Make getting a writer and writing an entry to csv thread safe
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/BufferedCsvWriter.java
Labels: bug, enhancement

#240 Fix file path for initialization of readers
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/CsvFileDefinition.java
  src/main/java/edu/ie3/datamodel/io/csv/HierarchicFileNamingStrategy.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
Labels: bug

#243 Adding ThermalBusInput to DefaultDirectoryHierarchy
  src/main/java/edu/ie3/datamodel/io/csv/DefaultDirectoryHierarchy.java
Labels: bug

#241 jh/#240 fix testcontainer image tags
  build.gradle
  src/test/groovy/edu/ie3/datamodel/io/sink/InfluxDbSinkIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSourceIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceIT.groovy
Labels: bug

#245 Leveraging threshold form maximum compression ratio
  src/main/java/edu/ie3/datamodel/io/TarballUtils.java
Labels: bug

#249 Resolve influxDBConnector issues
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/datamodel/io/connectors/InfluxDbConnector.java
  src/main/java/edu/ie3/datamodel/io/sink/InfluxDbSink.java
  src/test/groovy/edu/ie3/datamodel/io/sink/InfluxDbSinkIT.groovy
Labels: bug, invalid

#252 Consider proper ordering of coordinates when ensuring uniqueness of coordinates
  src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/GridAndGeoUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
Labels: bug
