Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2021-05, with the labels that each got.

#347 Add builder pattern to SubGridGate
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/graph/SubGridGate.java
  src/main/java/edu/ie3/datamodel/utils/ContainerUtils.java
  src/test/groovy/edu/ie3/test/common/ComplexTopology.groovy
Labels: bug

#357 Release v2.0.0
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
Labels: release

#355 Bugfixes from v2.0.0 release branch
  Jenkinsfile
  build.gradle
  src/main/java/edu/ie3/datamodel/io/connectors/CouchbaseConnector.java
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/DefaultDirectoryHierarchy.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessor.java
  src/main/java/edu/ie3/datamodel/io/sink/InfluxDbSink.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalBusInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalHouseInput.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/naming/HierarchicFileNamingStrategyTest.groovy
Labels: bug

#353 set version to 2.1.0
  CHANGELOG.md
  Jenkinsfile
  gradle/scripts/tests.gradle
  version.properties
Labels: release

#366 Log a warning instead of an error
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactory.java
Labels: invalid
