Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2022-07, with the labels that each got.

#619 Introduce thermal containers
  CHANGELOG.md
  docs/uml/main/input/ThermalDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/models/input/container/ThermalGrid.java
  src/main/java/edu/ie3/datamodel/models/input/container/ThermalUnits.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalBusInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalUnitInput.java
  src/test/groovy/edu/ie3/datamodel/models/input/container/SystemParticipantsTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/container/ThermalGridTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/container/ThermalUnitsTest.groovy
Labels: enhancement

#629 Remove workaround for spotless google-java-format
  gradle.properties
Labels: dependencies

#632 Adapting to changes in PowerSystemUnits
  CHANGELOG.md
  src/test/groovy/edu/ie3/datamodel/models/input/connector/LineInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/ValidationUtilsTest.groovy
Labels: bug

#566 Refactoring `TimeSeriesTypeSource` and cleaning up `CsvFileConnector`
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/TimeSeriesMetaInformationFactory.java
  src/main/java/edu/ie3/datamodel/io/naming/FileNamingStrategy.java
  src/main/java/edu/ie3/datamodel/io/naming/TimeSeriesMetaInformation.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMetaInformationSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesTypeSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMetaInformationSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesTypeSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMetaInformationSource.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/naming/FileNamingStrategyTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMetaInformationSourceIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMetaInformationSourceIT.groovy
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_c_2fcb3e53-b94a-4b96-bea4-c469e499f1a1.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_h_c8fe6547-fd85-4fdf-a169-e4da6ce5c3d0.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_p_9185b8c1-86ba-4a16-8dea-5ac898e8caa5.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_ph_76c9d846-797c-4f07-b7ec-2245f679f5c7.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_pq_3fbfaa97-cff4-46d4-95ba-a95665e87c26.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/its_pqh_46be1e57-e4ed-4ef7-95f1-b2b321cb2047.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_c.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_h.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_mapping.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_p.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_ph.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_pq.sql
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_pqh.sql
Labels: code quality
