Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2022-02, with the labels that each got.

#520 Don't mind me I'm just cleaning
  src/main/java/edu/ie3/datamodel/graph/ImpedanceWeightedGraph.java
Labels: enhancement

#536 Updating dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#550 use instanceof instead of getClass for equals methods in input models
  src/main/java/edu/ie3/datamodel/models/input/AssetInput.java
  src/main/java/edu/ie3/datamodel/models/input/AssetTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/MeasurementUnitInput.java
  src/main/java/edu/ie3/datamodel/models/input/NodeInput.java
  src/main/java/edu/ie3/datamodel/models/input/OperatorInput.java
  src/main/java/edu/ie3/datamodel/models/input/RandomLoadParameters.java
  src/main/java/edu/ie3/datamodel/models/input/connector/ConnectorInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/LineInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/SwitchInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer2WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/TransformerInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/LineTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/Transformer2WTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/Transformer3WTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/container/GraphicElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/GridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/JointGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/RawGridElements.java
  src/main/java/edu/ie3/datamodel/models/input/container/SubGridContainer.java
  src/main/java/edu/ie3/datamodel/models/input/container/SystemParticipants.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/GraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/LineGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/graphics/NodeGraphicInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvcsInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/HpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/PvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/characteristic/CharacteristicInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/characteristic/CharacteristicPoint.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/BmTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/ChpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/EvTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/SystemParticipantTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/WecTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/chargingpoint/ChargingPointType.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalHouseInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalUnitInput.java
Labels: bug, good first issue
