Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2023-04, with the labels that each got.

#789 Set fixed groovy version and update groovy to 4.0
  .github/dependabot.yml
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/test/groovy/edu/ie3/datamodel/io/sink/InfluxDbSinkIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceCosmoIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceIconIT.groovy
Labels: dependencies

#790 Removing deprecated classes and methods
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/graph/ImpedanceWeightedGraph.java
  src/main/java/edu/ie3/datamodel/graph/SubGridGate.java
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/CsvFileDefinition.java
  src/main/java/edu/ie3/datamodel/io/csv/FileNameMetaInformation.java
  src/main/java/edu/ie3/datamodel/io/csv/timeseries/ColumnScheme.java
  src/main/java/edu/ie3/datamodel/io/csv/timeseries/IndividualTimeSeriesMetaInformation.java
  src/main/java/edu/ie3/datamodel/io/csv/timeseries/LoadProfileTimeSeriesMetaInformation.java
  src/main/java/edu/ie3/datamodel/io/naming/EntityPersistenceNamingStrategy.java
  src/main/java/edu/ie3/datamodel/io/naming/FileNamingStrategy.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/FieldSourceToMethod.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/utils/GridAndGeoUtils.java
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvRawGridSourceTest.groovy
Labels: release

#724 Deprecating unused methods in FileNamingStrategy etc.
  src/main/java/edu/ie3/datamodel/io/naming/DefaultDirectoryHierarchy.java
  src/main/java/edu/ie3/datamodel/io/naming/FileHierarchy.java
  src/main/java/edu/ie3/datamodel/io/naming/FileNamingStrategy.java
  src/main/java/edu/ie3/datamodel/io/naming/FlatDirectoryHierarchy.java
Labels: code quality

#797 Fixing naming of heat pump result in documentation.
  docs/readthedocs/models/result/participant/hp.rst
Labels: documentation
