Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2023-11, with the labels that each got.

#919 Fixing spotless groovy
  gradle/scripts/spotless.gradle
Labels: bug

#907 Change from cleanup to cleanupSpec for BufferedCsvWriterTest
  CHANGELOG.md
  src/test/groovy/edu/ie3/datamodel/io/csv/BufferedCsvWriterTest.groovy
Labels: test

#932 Compare UUIDs instead of Strings.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/source/EntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/GraphicSource.java
  src/main/java/edu/ie3/datamodel/io/source/RawGridSource.java
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/test/groovy/edu/ie3/datamodel/io/source/EntitySourceTest.groovy
Labels: code quality

#940 Fixing sometimes failing tests
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CouchbaseConnector.java
  src/test/groovy/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSourceCosmoIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSourceIconIT.groovy
Labels: bug, test

#933 JavaDoc cautionary hint for `safeMapGet`.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/source/EntitySource.java
Labels: code quality

#945 Fix dev CI (removed plugin)
  Jenkinsfile
Labels: ci

#931 Abstracting some method in `ValidationUtils`.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/exceptions/DuplicateEntitiesException.java
  src/main/java/edu/ie3/datamodel/utils/ExceptionUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/GridContainerValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/ValidationUtilsTest.groovy
Labels: code quality
