Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2024-02, with the labels that each got.

#992 Pp/#875 fix electricvehicle documentation
  CHANGELOG.md
  docs/readthedocs/models/input/participant/ev.md
  docs/readthedocs/models/result/participant/ev.md
Labels: documentation

#1003 Implementing an evcs validation.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/exceptions/NotImplementedException.java
  src/main/java/edu/ie3/datamodel/utils/validation/ConnectorValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/GraphicValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/MeasurementUnitValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/NodeValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/ThermalUnitValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/ValidationUtilsTest.groovy
Labels: bug, enhancement

#999 CsvDataSource should throw exceptions on error.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/source/DataSource.java
  src/main/java/edu/ie3/datamodel/io/source/EntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/IdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/utils/Try.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/IdCoordinateSourceMock.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSourceCosmoIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSourceIconIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceIT.groovy
  src/test/groovy/edu/ie3/datamodel/utils/TryTest.groovy
  src/test/groovy/edu/ie3/test/common/WeatherTestData.groovy
Labels: bug, code quality

#1012 Introducing scaling function in copy builders
  CHANGELOG.md
  docs/readthedocs/io/csvfiles.md
  docs/readthedocs/models/input/participant/load.md
  docs/readthedocs/models/models.md
  src/main/java/edu/ie3/datamodel/exceptions/NotImplementedException.java
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/IconTimeBasedWeatherValueFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/input/InputEntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/sink/InfluxDbSink.java
  src/main/java/edu/ie3/datamodel/models/StandardUnits.java
  src/main/java/edu/ie3/datamodel/models/input/AssetTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/Transformer3WInput.java
  src/main/java/edu/ie3/datamodel/models/input/container/ThermalGrid.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvcsInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/HpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/PvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/BmTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/ChpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/EvTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/SystemParticipantTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/WecTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/chargingpoint/ChargingPointType.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalHouseInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalSinkInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalStorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalUnitInput.java
  src/main/java/edu/ie3/datamodel/utils/validation/GridContainerValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceCosmoIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceIconIT.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/BmInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/ChpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvcsInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/FixedFeedInInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/HpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/LoadInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/PvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/StorageInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/WecInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/BmTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/ChpTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/EvTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/HpTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/StorageTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/WecTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/chargingpoint/ChargingPointTypeTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/thermal/ThermalHouseInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/InvalidSystemParticipantTypeInput.groovy
Labels: enhancement, model

#1005 add maximum ac and dc charging limits to evtype
  CHANGELOG.md
  docs/readthedocs/models/input/participant/ev.md
  src/main/java/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/EvTypeInput.java
  src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTypeSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/EvTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/groovy/edu/ie3/test/common/TypeTestData.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_types/ev_type_input.csv
Labels: documentation, enhancement
