Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2024-11, with the labels that each got.

#1062 Improving the usage of streams on SQL fetches.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/SqlConnector.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlIdCoordinateSource.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/SqlConnectorIT.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/SqlSinkTest.groovy
Labels: java, io

#1113 Improving error message when using the outdated csv format
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/bm_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/evcs_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/fixed_feed_in_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/line_graphic_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/line_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/load_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/node_graphic_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/pv_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/storage_input.csv
Labels: bug, enhancement

#1188 Ensure that thermal boundaries of thermal house are not the same
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/utils/validation/ThermalUnitValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/ThermalUnitValidationUtilsTest.groovy
Labels: bug

#1193 Renamed timeseries mapping `participant` column to `asset`.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/TimeSeriesMappingFactory.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/utils/validation/UniquenessValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSourceIT.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/UniquenessValidationUtilsTest.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_timeseries/time_series_mapping.csv
  src/test/resources/edu/ie3/datamodel/io/source/sql/_timeseries/time_series_mapping.sql
Labels: enhancement
