Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2024-03, with the labels that each got.

#998 Pp/#825 enhance documentation for csv timeseries
  CHANGELOG.md
  docs/readthedocs/io/csvfiles.md
Labels: documentation

#1026 Enable persisting emUnits
  src/main/java/edu/ie3/datamodel/io/extractor/Extractor.java
  src/main/java/edu/ie3/datamodel/io/extractor/HasEm.java
  src/main/java/edu/ie3/datamodel/models/input/EmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/BmInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/ChpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/EvcsInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/FixedFeedInInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/HpInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/PvInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/StorageInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/SystemParticipantInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/WecInput.java
  src/test/groovy/edu/ie3/datamodel/io/extractor/ExtractorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/BmInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/ChpInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EmInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/HpInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/PvInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/StorageInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/WecInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/BmInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/ChpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EmInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/EvcsInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/FixedFeedInInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/HpInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/LoadInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/PvInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/StorageInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/WecInputTest.groovy
Labels: enhancement, io

#1038 Fixing equals in `ResultEntity` and `TimeSeriesEntry`
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/models/result/ResultEntity.java
  src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeriesEntry.java
Labels: bug

#1041 Release 5.0.1
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/edu/ie3/datamodel/models/result/ResultEntity.java
  src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeriesEntry.java
  version.properties
Labels: release

#1036 Fix line.md documentation
  docs/readthedocs/models/input/grid/line.md
Labels: documentation
