Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2024-06, with the labels that each got.

#1092 `GridContainerValidationUtils` checks the connectivity for all defined operation time intervals.
  CHANGELOG.md
  docs/readthedocs/io/ValidationUtils.md
  src/main/java/edu/ie3/datamodel/utils/validation/GridContainerValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/GridContainerValidationUtilsTest.groovy
Labels: enhancement

#942 adapting dod in documentation
  CHANGELOG.md
  docs/readthedocs/models/input/participant/storage.md
  docs/uml/main/input/SystemDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactory.java
  src/main/java/edu/ie3/datamodel/models/StandardUnits.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/typeinput/SystemParticipantTypeInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTypeSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/StorageTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/groovy/edu/ie3/test/common/TypeTestData.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/storage_type_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_types/storage_type_input.csv
Labels: documentation

#1031 Refactor `CsvFileConnector` and `CsvDataSource`.
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/main/java/edu/ie3/datamodel/io/csv/CsvFileDefinition.java
  src/main/java/edu/ie3/datamodel/io/sink/CsvFileSink.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMetaInformationSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/csv/CsvFileDefinitionTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
Labels: code quality

#1098 Adding `CongestionResult`.
  CHANGELOG.md
  docs/readthedocs/models/models.md
  docs/readthedocs/models/result/grid/congestion.md
  src/main/java/edu/ie3/datamodel/io/factory/result/CongestionResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/FlexOptionsResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ModelResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/NodeResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ResultEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/SwitchResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ThermalResultFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/result/ResultEntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/source/ResultEntitySource.java
  src/main/java/edu/ie3/datamodel/models/result/CongestionResult.java
  src/main/java/edu/ie3/datamodel/models/result/ModelResultEntity.java
  src/main/java/edu/ie3/datamodel/models/result/NodeResult.java
  src/main/java/edu/ie3/datamodel/models/result/ResultEntity.java
  src/main/java/edu/ie3/datamodel/models/result/connector/ConnectorResult.java
  src/main/java/edu/ie3/datamodel/models/result/connector/SwitchResult.java
  src/main/java/edu/ie3/datamodel/models/result/system/FlexOptionsResult.java
  src/main/java/edu/ie3/datamodel/models/result/system/SystemParticipantResult.java
  src/main/java/edu/ie3/datamodel/models/result/thermal/ThermalUnitResult.java
  src/main/java/edu/ie3/datamodel/utils/validation/UniquenessValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/UniquenessValidationUtilsTest.groovy
Labels: enhancement

#1100 Fixing entries in `CHANGELOG`.
  CHANGELOG.md
Labels: documentation

#1105 Fixing project being build twice in CI
  CHANGELOG.md
  Jenkinsfile
Labels: bug, ci

#1044 Abstract commonly used functionality from `EntitySource`.
  CHANGELOG.md
  docs/uml/main/EntitySourceClassDiagram.puml
  src/main/java/edu/ie3/datamodel/io/factory/input/AssetInputEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/ConnectorInputEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/Transformer3WInputEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ResultEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/source/AssetEntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/EnergyManagementSource.java
  src/main/java/edu/ie3/datamodel/io/source/EntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/GraphicSource.java
  src/main/java/edu/ie3/datamodel/io/source/IdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/RawGridSource.java
  src/main/java/edu/ie3/datamodel/io/source/ResultEntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/TypeSource.java
  src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
  src/main/java/edu/ie3/datamodel/utils/QuadFunction.java
  src/main/java/edu/ie3/datamodel/utils/Try.java
  src/test/groovy/edu/ie3/datamodel/io/source/AssetEntitySourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/DummyDataSource.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/EntitySourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/IdCoordinateSourceMock.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/SystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/ThermalSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvGraphicSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvRawGridSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/TryTest.groovy
  src/test/groovy/edu/ie3/test/common/WeatherTestData.groovy
Labels: code quality, io

#1109 Merge back changes from rel 5.1
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  version.properties
Labels: release
