Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2024-01, with the labels that each got.

#980 pp/#965 fix hyperlink in line documentation
  CHANGELOG.md
  docs/readthedocs/models/input/grid/line.md
Labels: documentation

#971 Enhancing Try with commonly used methods
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/utils/Try.java
  src/test/groovy/edu/ie3/datamodel/utils/TryTest.groovy
Labels: enhancement

#995 Pp/#737 update contributingmd
  AUTHORS
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#887 Fix path at time series mapping
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
  src/test/groovy/edu/ie3/datamodel/io/csv/BufferedCsvWriterTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
Labels: bug

#988 Adding log message when using SwitchInputs with `parallelDevices`
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/factory/input/SwitchInputFactory.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/SwitchInputFactoryTest.groovy
Labels: enhancement
