Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2025-01, with the labels that each got.

#1202 Mh/#1195 removing dsm attribute
  CHANGELOG.md
  docs/readthedocs/models/input/participant/load.md
  docs/uml/main/input/SystemDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/system/LoadInput.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/input/InputEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/LoadInputTest.groovy
  src/test/groovy/edu/ie3/test/common/SampleJointGrid.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/resources/edu/ie3/datamodel/io/sink/_sql/input_entities.sql
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/load_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/load_input.csv
Labels: model

#1224 Fix spotless deprecations
  CHANGELOG.md
  gradle/scripts/spotless.gradle
Labels: code quality

#1217 Extend ValidationUtils for validating ThermalGrids
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/utils/validation/ThermalValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/ThermalValidationUtilsTest.groovy
Labels: enhancement
