Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2025-07, with the labels that each got.

#1361 Fixed valid fields for `EmInput`
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/factory/input/AssetInputEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/EmInputFactory.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/AssetInputEntityFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/EmInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
Labels: bug

#1359 Extend Validation to EnergyManagement Systems
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/utils/validation/EnergyManagementValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/ValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/EmValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/GridTestData.groovy
Labels: enhancement, test

#1355 Improved error messages when reading and validating an invalid grid
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/exceptions/DuplicateEntitiesException.java
  src/main/java/edu/ie3/datamodel/exceptions/FailedValidationException.java
  src/main/java/edu/ie3/datamodel/exceptions/InvalidEntityException.java
  src/main/java/edu/ie3/datamodel/exceptions/SourceException.java
  src/main/java/edu/ie3/datamodel/io/factory/Factory.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/source/EntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/GraphicSource.java
  src/main/java/edu/ie3/datamodel/io/source/RawGridSource.java
  src/main/java/edu/ie3/datamodel/io/source/ResultEntitySource.java
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
  src/main/java/edu/ie3/datamodel/io/source/TimeSeriesMappingSource.java
  src/main/java/edu/ie3/datamodel/io/source/TypeSource.java
  src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvJointGridContainerSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvLoadProfileSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
  src/main/java/edu/ie3/datamodel/utils/ExceptionUtils.java
  src/main/java/edu/ie3/datamodel/utils/Try.java
  src/main/java/edu/ie3/datamodel/utils/validation/GridContainerValidationUtils.java
  src/main/java/edu/ie3/datamodel/utils/validation/UniquenessValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/source/EnergyManagementSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/EntitySourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/TimeSeriesMappingSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvGraphicSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvRawGridSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/TryTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/UniquenessValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/ValidationUtilsTest.groovy
Labels: enhancement

#1385 Enhanced check for invalid field names in sources
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/factory/Factory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/SystemParticipantInputEntityFactory.java
  src/test/groovy/edu/ie3/datamodel/io/factory/FactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/bm_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/evcs_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/fixed_feed_in_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/load_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/pv_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/storage_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_joint_grid/wec_input.csv
Labels: bug, enhancement

#1312 Adding updated `BdewStandardLoadProfiles`.
  CHANGELOG.md
  docs/readthedocs/io/csvfiles.md
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/BdewLoadProfileFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/timeseries/LoadProfileFactory.java
  src/main/java/edu/ie3/datamodel/io/processor/EntityProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/GetterMethod.java
  src/main/java/edu/ie3/datamodel/io/processor/Processor.java
  src/main/java/edu/ie3/datamodel/io/processor/ProcessorProvider.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/FieldSourceToMethod.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessor.java
  src/main/java/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessorKey.java
  src/main/java/edu/ie3/datamodel/io/source/LoadProfileSource.java
  src/main/java/edu/ie3/datamodel/io/source/csv/CsvLoadProfileSource.java
  src/main/java/edu/ie3/datamodel/io/source/sql/SqlLoadProfileSource.java
  src/main/java/edu/ie3/datamodel/models/BdewSeason.java
  src/main/java/edu/ie3/datamodel/models/profile/BdewStandardLoadProfile.java
  src/main/java/edu/ie3/datamodel/models/value/load/BdewLoadValues.java
  src/main/java/edu/ie3/datamodel/models/value/load/LoadValues.java
  src/main/java/edu/ie3/datamodel/models/value/load/RandomLoadValues.java
  src/main/resources/load/lpts_g25.csv
  src/main/resources/load/lpts_h25.csv
  src/main/resources/load/lpts_l25.csv
  src/main/resources/load/lpts_p25.csv
  src/main/resources/load/lpts_s25.csv
  src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/BdewLoadProfileFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/ProcessorProviderTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/processor/timeseries/TimeSeriesProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/LoadProfileSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/profile/LoadProfileTest.groovy
  src/test/groovy/edu/ie3/resources/load/BdewLoadProfileTest.groovy
  src/test/groovy/edu/ie3/test/common/TimeSeriesTestData.groovy
Labels: enhancement

#1358 Enhance ValidationUtils for load profile
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
Labels: test

#1402 Df/#1401 merge back 8.1.0
  CHANGELOG.md
  CITATION.cff
Labels: release

#1391 add weathersource docs
  CHANGELOG.md
  docs/readthedocs/models/input/additionaldata/weathersource.md
  docs/readthedocs/models/models.md
Labels: documentation

#1404 Updated CI-Pipeline to run task `Deploy` and `Staging` only for `Main`
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: ci
