Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2025-03, with the labels that each got.

#1282 Implementation of GHA Pipeline for PSDM
  .github/workflows/ci.yml
  CHANGELOG.md
  build.gradle
  gradle/scripts/branchName.gradle
  scripts/branch_type.sh
  scripts/get_versions.sh
  scripts/run-version-check.sh
  scripts/version_check.sh
Labels: enhancement, ci

#1285 Fixed test report path for SonarQube
  CHANGELOG.md
  build.gradle
  gradle/scripts/semVer.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/tests.gradle
Labels: bug, ci

#1277 Mh/#1275 new copy builders
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/models/input/AssetTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/LineTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/Transformer2WTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/connector/type/Transformer3WTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/BmTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/ChpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/EvTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/StorageTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/SystemParticipantTypeInput.java
  src/main/java/edu/ie3/datamodel/models/input/system/type/WecTypeInput.java
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/BmTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/ChpTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/system/type/HpTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/typeInput/LineTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/typeInput/Transformer2WTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/typeInput/Transformer3WTypeInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/InvalidAssetTypeInput.groovy
Labels: enhancement
