Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2025-05, with the labels that each got.

#1316 Removing Jenkinsfile
  CHANGELOG.md
  Jenkinsfile
Labels: ci

#1318 Updating readthedocs config
  .readthedocs.yaml
  CHANGELOG.md
Labels: documentation

#1329 Updated dependabot workflow and added CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  CHANGELOG.md
Labels: dependencies, ci

#1326 Fixed handling of `CongestionResult.InputModelType` in `EntityProcessor`
  CHANGELOG.md
  src/main/java/edu/ie3/datamodel/io/processor/Processor.java
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
Labels: bug

#1332 Fixed em fields in input models.
  CHANGELOG.md
  docs/readthedocs/models/input/em.md
  docs/readthedocs/models/input/participant/bm.md
  docs/readthedocs/models/input/participant/chp.md
  docs/readthedocs/models/input/participant/ev.md
  docs/readthedocs/models/input/participant/evcs.md
  docs/readthedocs/models/input/participant/fixedfeedin.md
  docs/readthedocs/models/input/participant/hp.md
  docs/readthedocs/models/input/participant/load.md
  docs/readthedocs/models/input/participant/pv.md
  docs/readthedocs/models/input/participant/storage.md
  docs/readthedocs/models/input/participant/wec.md
  src/main/java/edu/ie3/datamodel/io/factory/input/EmAssetInputEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/EmInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/BmInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/ChpInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/EvInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/HpInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/LoadInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/PvInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/StorageInputFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/SystemParticipantEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/SystemParticipantInputEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/SystemParticipantTypedEntityData.java
  src/main/java/edu/ie3/datamodel/io/factory/input/participant/WecInputFactory.java
  src/main/java/edu/ie3/datamodel/io/source/EnergyManagementSource.java
  src/main/java/edu/ie3/datamodel/io/source/SystemParticipantSource.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/EmInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/FixedFeedInInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/EnergyManagementSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/SystemParticipantSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvDataSourceTest.groovy
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/bm_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/chp_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/cylindrical_storage_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/em_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/ev_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/evcs_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/fixed_feed_in_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/hp_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/load_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/pv_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/storage_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/wec_input.csv
Labels: bug
