Repository ie3-institute/PowerSystemDataModel, pull requests merged in 2025-02, with the labels that each got.

#1235 Refactoring `CongestionResult`
  CHANGELOG.md
  docs/readthedocs/models/result/grid/congestion.md
  src/main/java/edu/ie3/datamodel/io/factory/result/CongestionResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ConnectorResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/FlexOptionsResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ModelResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/NodeResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ResultEntityFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/SwitchResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/SystemParticipantResultFactory.java
  src/main/java/edu/ie3/datamodel/io/factory/result/ThermalResultFactory.java
  src/main/java/edu/ie3/datamodel/models/result/CongestionResult.java
  src/main/java/edu/ie3/datamodel/models/result/ModelResultEntity.java
  src/main/java/edu/ie3/datamodel/models/result/NodeResult.java
  src/main/java/edu/ie3/datamodel/models/result/ResultEntity.java
  src/main/java/edu/ie3/datamodel/models/result/connector/ConnectorResult.java
  src/main/java/edu/ie3/datamodel/models/result/connector/SwitchResult.java
  src/main/java/edu/ie3/datamodel/models/result/system/FlexOptionsResult.java
  src/main/java/edu/ie3/datamodel/models/result/system/SystemParticipantResult.java
  src/main/java/edu/ie3/datamodel/models/result/thermal/ThermalUnitResult.java
  src/main/java/edu/ie3/datamodel/utils/validation/UniquenessValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/processor/result/ResultEntityProcessorTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/UniquenessValidationUtilsTest.groovy
Labels: enhancement

#1245 Fixed example in ReadTheDocs
  CHANGELOG.md
  docs/readthedocs/models/input/operator.md
Labels: documentation

#1252 Introduce thermal power for thermal storages
  CHANGELOG.md
  docs/readthedocs/models/input/thermal/cylindricalstorage.md
  docs/readthedocs/models/result/participant/cylindricalstorage.md
  docs/uml/main/input/ThermalDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
  src/main/java/edu/ie3/datamodel/utils/validation/ThermalValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/extractor/ExtractorTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/CsvFileSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/sink/SqlSinkTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvThermalSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/ThermalValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/SystemParticipantTestData.groovy
  src/test/groovy/edu/ie3/test/common/ThermalUnitInputTestData.groovy
  src/test/resources/edu/ie3/datamodel/io/sink/_sql/input_entities.sql
  src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/cylindrical_storage_input.csv
  src/test/resources/edu/ie3/datamodel/io/source/csv/_thermal/cylindrical_storage_input.csv
Labels: enhancement

#1254 Add Attributes housingType and numberInhabitants to ThermalHouses
  CHANGELOG.md
  docs/readthedocs/io/ValidationUtils.md
  docs/readthedocs/models/input/thermal/thermalhouse.md
  docs/uml/main/input/ThermalDatamodelConcept.puml
  src/main/java/edu/ie3/datamodel/io/factory/input/ThermalHouseInputFactory.java
  src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalHouseInput.java
  src/main/java/edu/ie3/datamodel/utils/validation/ThermalValidationUtils.java
  src/test/groovy/edu/ie3/datamodel/io/factory/input/ThermalHouseInputFactoryTest.groovy
  src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvThermalSourceTest.groovy
  src/test/groovy/edu/ie3/datamodel/models/input/thermal/ThermalHouseInputTest.groovy
  src/test/groovy/edu/ie3/datamodel/utils/validation/ThermalValidationUtilsTest.groovy
  src/test/groovy/edu/ie3/test/common/ThermalUnitInputTestData.groovy
  src/test/resources/edu/ie3/datamodel/io/sink/_sql/input_entities.sql
  src/test/resources/edu/ie3/datamodel/io/source/csv/_thermal/thermal_house_input.csv
Labels: enhancement, model

#1262 Remove double test in ThermalValidationUtils
  CHANGELOG.md
  src/test/groovy/edu/ie3/datamodel/utils/validation/ThermalValidationUtilsTest.groovy
Labels: bug, code quality, test

#1259 Adding validation for bdew load profile sources.
  CHANGELOG.md
  src/main/resources/load/lpts_g5.csv
  src/test/groovy/edu/ie3/resources/load/BdewLoadProfileTest.groovy
Labels: enhancement

#1265 Updating gradle to v8.13
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies
